### ISSUE TITLE
Appears dysfunctional on Windows

### ISSUE THREAD

**Issue by popey456963** [aam229/inquirer-path#2]
![](https://puu.sh/wDvbq/496caa8853.png)

In this example, only the second line should query for a file, the fourth line is an anomaly not entered within the code.  Whilst typing in, the third entry defaulted to containing the answer to the previous query, and when backspaced that still led to an invalid answer to the third query.

Configuration:

    {
      type: 'path',
      name: 'file',
      message: 'Which file would you like to parse?',
      default: process.cwd(),
      validate: (path) => {
        if (fs.existsSync(path)) return true
        return console.log(' <-- this path does not exist or is inaccesible.')
      },
      multi: false
    }

**Comment by aam229** [comment]
Thank you for the feedback, it allowed me to fix a lot of issues:
 - Format paths that use the `\` separator properly. Typing in `C:\Documen` and hitting tab would generate the path `C:\\Document and Settings` instead of `C:\Document and Settings\`
 - Handle permission exceptions on the file system. It would crash when trying to scan/access a directory/file that the user does not have access to. This would happen when using the autocomplete feature.
 - Clean up event listeners properly. The `onKeyDown` listener did not get unregistered once the question had been answered causing the prompt to randomly rerender itself while answering later questions.
 - Fix the last render (once the question has been answered). The render phase used to always resets the user input to match the internal state. For the final render, the input has already been cleaned up for the next question and therefore should not be touched. 

Please let me know if you have any other issues/feedback.
